import { Language, Voice } from './types';

// Helper to assign voices cyclically to ensure variety (Fallback)
const VOICES = ['Puck', 'Charon', 'Kore', 'Fenrir', 'Zephyr'];
const getVoice = (index: number) => VOICES[index % VOICES.length];

export const AVAILABLE_VOICES: Voice[] = [
  { id: 'Kore', name: 'Sarah', gender: 'Female', description: 'Calm & Professional' },
  { id: 'Fenrir', name: 'Michael', gender: 'Male', description: 'Deep & Authoritative' },
  { id: 'Zephyr', name: 'Emma', gender: 'Female', description: 'Soft & Helpful' },
  { id: 'Charon', name: 'David', gender: 'Male', description: 'Clear & Direct' },
  { id: 'Puck', name: 'Alex', gender: 'Neutral', description: 'Playful & Energetic' },
];

// Extensive list of languages covering all major regions
const RAW_LANGUAGES = [
  { code: 'af-ZA', name: 'Afrikaans' },
  { code: 'sq-AL', name: 'Albanian' },
  { code: 'am-ET', name: 'Amharic' },
  { code: 'ar-SA', name: 'Arabic' },
  { code: 'hy-AM', name: 'Armenian' },
  { code: 'az-AZ', name: 'Azerbaijani' },
  { code: 'eu-ES', name: 'Basque' },
  { code: 'bn-BD', name: 'Bengali' },
  { code: 'bs-BA', name: 'Bosnian' },
  { code: 'bg-BG', name: 'Bulgarian' },
  { code: 'ca-ES', name: 'Catalan' },
  { code: 'ceb-PH', name: 'Cebuano' },
  { code: 'zh-CN', name: 'Chinese (Mandarin)' },
  { code: 'zh-TW', name: 'Chinese (Taiwan)' },
  { code: 'zh-HK', name: 'Chinese (Cantonese)' },
  { code: 'co-FR', name: 'Corsican' },
  { code: 'hr-HR', name: 'Croatian' },
  { code: 'cs-CZ', name: 'Czech' },
  { code: 'da-DK', name: 'Danish' },
  { code: 'nl-NL', name: 'Dutch' },
  { code: 'en-US', name: 'English (US)' },
  { code: 'en-GB', name: 'English (UK)' },
  { code: 'en-AU', name: 'English (Australia)' },
  { code: 'en-IN', name: 'English (India)' },
  { code: 'eo-EO', name: 'Esperanto' },
  { code: 'et-EE', name: 'Estonian' },
  { code: 'fi-FI', name: 'Finnish' },
  { code: 'fr-FR', name: 'French' },
  { code: 'fy-NL', name: 'Frisian' },
  { code: 'gl-ES', name: 'Galician' },
  { code: 'ka-GE', name: 'Georgian' },
  { code: 'de-DE', name: 'German' },
  { code: 'el-GR', name: 'Greek' },
  { code: 'gu-IN', name: 'Gujarati' },
  { code: 'ht-HT', name: 'Haitian Creole' },
  { code: 'ha-NE', name: 'Hausa' },
  { code: 'haw-US', name: 'Hawaiian' },
  { code: 'he-IL', name: 'Hebrew' },
  { code: 'hi-IN', name: 'Hindi' },
  { code: 'hmn-CN', name: 'Hmong' },
  { code: 'hu-HU', name: 'Hungarian' },
  { code: 'is-IS', name: 'Icelandic' },
  { code: 'ig-NG', name: 'Igbo' },
  { code: 'id-ID', name: 'Indonesian' },
  { code: 'ga-IE', name: 'Irish' },
  { code: 'it-IT', name: 'Italian' },
  { code: 'ja-JP', name: 'Japanese' },
  { code: 'jv-ID', name: 'Javanese' },
  { code: 'kn-IN', name: 'Kannada' },
  { code: 'kk-KZ', name: 'Kazakh' },
  { code: 'km-KH', name: 'Khmer' },
  { code: 'ko-KR', name: 'Korean' },
  { code: 'ku-TR', name: 'Kurdish' },
  { code: 'ky-KG', name: 'Kyrgyz' },
  { code: 'lo-LA', name: 'Lao' },
  { code: 'la-VA', name: 'Latin' },
  { code: 'lv-LV', name: 'Latvian' },
  { code: 'lt-LT', name: 'Lithuanian' },
  { code: 'lb-LU', name: 'Luxembourgish' },
  { code: 'mk-MK', name: 'Macedonian' },
  { code: 'mg-MG', name: 'Malagasy' },
  { code: 'ms-MY', name: 'Malay' },
  { code: 'ml-IN', name: 'Malayalam' },
  { code: 'mt-MT', name: 'Maltese' },
  { code: 'mi-NZ', name: 'Maori' },
  { code: 'mr-IN', name: 'Marathi' },
  { code: 'mn-MN', name: 'Mongolian' },
  { code: 'my-MM', name: 'Myanmar (Burmese)' },
  { code: 'ne-NP', name: 'Nepali' },
  { code: 'no-NO', name: 'Norwegian' },
  { code: 'ny-MW', name: 'Nyanja (Chichewa)' },
  { code: 'ps-AF', name: 'Pashto' },
  { code: 'fa-IR', name: 'Persian' },
  { code: 'pl-PL', name: 'Polish' },
  { code: 'pt-PT', name: 'Portuguese (Portugal)' },
  { code: 'pt-BR', name: 'Portuguese (Brazil)' },
  { code: 'pa-IN', name: 'Punjabi' },
  { code: 'ro-RO', name: 'Romanian' },
  { code: 'ru-RU', name: 'Russian' },
  { code: 'sm-WS', name: 'Samoan' },
  { code: 'gd-GB', name: 'Scots Gaelic' },
  { code: 'sr-RS', name: 'Serbian' },
  { code: 'st-LS', name: 'Sesotho' },
  { code: 'sn-ZW', name: 'Shona' },
  { code: 'sd-PK', name: 'Sindhi' },
  { code: 'si-LK', name: 'Sinhala' },
  { code: 'sk-SK', name: 'Slovak' },
  { code: 'sl-SI', name: 'Slovenian' },
  { code: 'so-SO', name: 'Somali' },
  { code: 'es-ES', name: 'Spanish' },
  { code: 'su-ID', name: 'Sundanese' },
  { code: 'sw-KE', name: 'Swahili' },
  { code: 'sv-SE', name: 'Swedish' },
  { code: 'tl-PH', name: 'Tagalog (Filipino)' },
  { code: 'tg-TJ', name: 'Tajik' },
  { code: 'ta-IN', name: 'Tamil' },
  { code: 'te-IN', name: 'Telugu' },
  { code: 'th-TH', name: 'Thai' },
  { code: 'tr-TR', name: 'Turkish' },
  { code: 'uk-UA', name: 'Ukrainian' },
  { code: 'ur-PK', name: 'Urdu' },
  { code: 'uz-UZ', name: 'Uzbek' },
  { code: 'vi-VN', name: 'Vietnamese' },
  { code: 'cy-GB', name: 'Welsh' },
  { code: 'xh-ZA', name: 'Xhosa' },
  { code: 'yi-DE', name: 'Yiddish' },
  { code: 'yo-NG', name: 'Yoruba' },
  { code: 'zu-ZA', name: 'Zulu' }
];

export const SUPPORTED_LANGUAGES: Language[] = RAW_LANGUAGES.map((lang, index) => ({
  code: lang.code,
  name: lang.name,
  flag: '🌐', // Using a generic globe for consistency across 100+ languages
  voiceName: getVoice(index)
})).sort((a, b) => a.name.localeCompare(b.name));

export const MODEL_NAME = 'gemini-2.5-flash-native-audio-preview-09-2025';